#!/bin/sh
#
#  Create the League Fixture List for the web page
#
#  Edit the teams array (below)
#  .. then run the program.  It will prompt you to type in a date, then the
#  two teams playing, just the numbers without any spaces.
#  The html ends up in $OUT, and can be pasted into the web page
#
#  The results00.html file can then be read by the league table program
#  .. stats/mkleague
# 

OUT=fixturelist

team() {
	case $1 in
		1)	echo -n "Smith &amp; Nephew" ;;
		2)	echo -n "Bioaccumulator" ;;
		3)	echo -n "Physical Wrecks" ;;
		4)	echo -n "PLONGE" ;;
		5)	echo -n "All Out Chemists" ;;
		6)	echo -n "Heavy Rollers" ;;
		7)	echo -n "PDP XI";;
		8)	echo -n "Wentworth";;
		9)	echo -n "IRISS XI";;
		*)	echo -n "WHO?";;
	esac
}

echo -n 'day: '

while read day
do
	echo -n '12: '
	read teams
	echo -n "<tr><td rowspan=2>$day <td> " >> $OUT
	team `echo $teams | cut -c1` >> $OUT
	echo "<td> <td rowspan=2> " >> $OUT
	echo -n "<tr><td> " >> $OUT
	team `echo $teams | cut -c2` >> $OUT
	echo "<td> " >> $OUT
	echo -n 'day: '
done
