apiVersion: v1
kind: Service
metadata:
  name: web-app-backend
  namespace: web
  labels:
    app: web-app-backend
    component: backend
spec:
  type: ClusterIP
  selector:
    app: web-app-backend
  ports:
  - name: http
    port: 3080
    targetPort: 3080
    protocol: TCP
  sessionAffinity: None
