apiVersion: v1
kind: PersistentVolume
metadata:
  name: comics-images-pv
  labels:
    app: web
    component: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/k3s-storage/comics-images
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comics-images-pvc
  labels:
    app: web
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: comics-images-pv
