apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - photos-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  app.kubernetes.io/name: web-app
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/mcharno/web-app-backend
    newTag: latest
  - name: ghcr.io/mcharno/web-app-frontend
    newTag: latest
